name: CI

on:
  push:
    branches:
       - main
       - jenk
  workflow_dispatch:     

jobs:
  my_first_jobs:
    runs-on: ubuntu-latest
  
    steps:
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Show version
      run: "java -version"
      
    - name: Get repo
      uses: actions/checkout@v3
      with:
        ref: jenk
         
    - name: Install dependencies
      run: "mvn compile"
      
    - name: Build with Maven
      run: "mvn package -DskipTests"

    - name: Test app
      run: "mvn test" 
